version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_contenidor
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: elementos
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    container_name: backend_contenidor
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    command: ["./wait-for-it.sh", "mysql:3306", "--", "php", "-S", "0.0.0.0:8000"]

  frontend:
    build: ./frontend
    container_name: frontend_contenidor
    depends_on:
      - backend
    ports:
      - "8080:8080"
    command: ["npm", "run", "serve"]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: adminMySQL_contenidor
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"

volumes:
  db_data:
